#!/usr/bin/python
#
# Bootstrap file to easily start the proxmark3 docker.
#
import os
import grp
import sys

common_opts = ['docker', 'run', '--rm', '-ti', '--net=none',
               '--security-opt=no-new-privileges']

if len(sys.argv) <= 1:
    args = common_opts + ['proxmark3']
    os.execvp(args[0], args)
    sys.exit(1)

if sys.argv[1] in ['-h', '-m']:
    args = common_opts + ['proxmark3', sys.argv[1]]
    os.execvp(args[0], args)
    sys.exit(1)

try:
    device_gid = os.stat(sys.argv[1]).st_gid
except OSError as e:
    sys.stderr.write("{}\n".format(e))
    sys.exit(1)

dialout_gid = grp.getgrnam('dialout').gr_gid
if dialout_gid != device_gid:
    try:
        name = '(' + grp.getgrgid(device_gid).gr_name + ')'
    except KeyError:
        name = ""

    msg = "'{}' gid={}{} instead of {}(dialout).\n"
    msg = msg.format(sys.argv[1], device_gid, name, dialout_gid)
    sys.stderr.write(msg)
    sys.exit(1)

args  = common_opts
args += ['--device={}:/dev/ttyACM0'.format(sys.argv[1]),
         '--group-add={}'.format(device_gid),
         'proxmark3', '/dev/ttyACM0']

os.execvp(args[0], args)
